# Generated by Django 5.0.3 on 2024-03-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1024)),
                ('genre', models.CharField(max_length=255)),
                ('tempo', models.FloatField()),
                ('average_spectral_centroid', models.FloatField()),
                ('average_spectral_rolloff', models.FloatField()),
                ('average_spectral_contrast', models.TextField()),
                ('mfccs_mean', models.TextField()),
                ('average_chroma_stft', models.FloatField()),
                ('average_rms_energy', models.FloatField()),
            ],
        ),
    ]
