# Generated by Django 5.0.3 on 2024-03-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songfeature',
            name='scene',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
