# Generated by Django 5.0.3 on 2024-03-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_songfeature_scene'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='songfeature',
            name='relevant_genres',
            field=models.TextField(default='[]'),
        ),
    ]
