# Generated by Django 5.0.3 on 2024-03-19 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_genrerelationship_songfeature_relevant_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text="The genre's slug, a URL-friendly version of its name.", max_length=255, unique=True)),
                ('genre', models.CharField(help_text='The name of the genre.', max_length=255)),
                ('scene', models.CharField(blank=True, help_text='The scene from which this genre originated.', max_length=255, null=True)),
                ('emerged', models.CharField(blank=True, help_text='The approximate period or decade when this genre first emerged.', max_length=255, null=True)),
                ('aka', models.TextField(default='[]', help_text='Other names or aliases for the genre.')),
                ('duration_start', models.IntegerField(blank=True, help_text="The year when the genre's distinct period started.", null=True)),
                ('duration_end', models.IntegerField(blank=True, help_text="The year when the genre's distinct period ended or the current year if it's ongoing.", null=True)),
                ('parent_genre', models.ForeignKey(blank=True, help_text='The parent genre from which this genre arose.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_genres', to='myapp.genreinfo')),
            ],
        ),
    ]
