# Generated by Django 5.0.3 on 2024-03-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_genrerelationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songfeature',
            options={'verbose_name': 'Song Feature', 'verbose_name_plural': 'Song Features'},
        ),
    ]
