# Generated by Django 5.0.3 on 2024-03-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_songfeature_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='songfeature',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
