# Generated by Django 5.0.3 on 2024-04-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_songfeature_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='songfeature',
            name='vggish_embeddings',
            field=models.TextField(default='[]'),
        ),
    ]
