# Generated by Django 5.0.3 on 2024-04-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_songfeature_vggish_embeddings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songfeature',
            name='relevant_genres',
        ),
    ]
